/**
 * Instant Win Helper - UPDATED FOR COMPETITIONVRF v2.5 CONTRACT
 *
 * This module provides helper functions for instant win prize management.
 *
 * ARCHITECTURE UPDATE:
 * The new CompetitionVRF v2.5 contract (0x8ce54644e3313934D663c43Aea29641DFD8BcA1A) focuses
 * on VRF-based winner selection for standard competitions. Instant win functionality
 * is managed separately through the database.
 *
 * This helper now focuses on:
 * - Database synchronization for prize tracking
 * - Winner notification
 * - Legacy support for non-contract competitions
 */

import { StagingRNG } from './rng-utils';

/**
 * Helper to create an instant win prize directly using Supabase
 */
async function createInstantWinPrize(prize: {
  UID: string;
  competitionId: string;
  winningTicket: number;
  prize: string;
  url: string;
  description: string;
  priority: number;
  winningWalletAddress: string | null;
  avatarUrl: string | null;
}) {
  const { supabase } = await import('./supabase');

  // Validate UUID format
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (prize.competitionId && !uuidRegex.test(prize.competitionId)) {
    throw new Error('Invalid competitionId format. Must be a valid UUID.');
  }

  const prizeData = {
    UID: prize.UID || crypto.randomUUID(),
    competitionId: prize.competitionId || null,
    prize: prize.prize || null,
    url: prize.url || null,
    description: prize.description || null,
    priority: prize.priority || 0,
    winningTicket: prize.winningTicket || null,
    winningWalletAddress: prize.winningWalletAddress || null,
    avatarUrl: prize.avatarUrl || null,
  };

  const { data, error } = await supabase
    .from('Prize_Instantprizes')
    .insert(prizeData as any)
    .select()
    .maybeSingle();

  if (error) {
    console.error('Error creating instant win prize:', error);
    throw error;
  }

  return data;
}

/**
 * Helper functions for instant win prize management
 */
export const instantWinHelper = {
  /**
   * Generate winning tickets for a competition
   *
   * NOTE: For CompetitionSystemV3 INSTANT_WIN competitions, winning tickets
   * are determined on-chain by the VRF seed. This function is for:
   * - Legacy competitions
   * - Pre-populating database for tracking
   * - Admin reporting purposes
   *
   * @deprecated For new competitions, use CompetitionSystemV3 contract
   */
  async generateWinningTicketsForCompetition(
    competitionUid: string,
    totalTickets: number,
    prizes: Array<{ prize: string; count: number; url: string; description: string; priority: number }>
  ): Promise<boolean> {
    console.warn(
      '[instantWinHelper] generateWinningTicketsForCompetition is for legacy support. ' +
      'New INSTANT_WIN competitions use on-chain VRF via CompetitionSystemV3.'
    );

    try {
      const totalWinners = prizes.reduce((sum, p) => sum + p.count, 0);

      if (totalWinners < 10 || totalWinners > 50) {
        throw new Error('Total winning tickets must be between 10 and 50');
      }

      const winningTickets = StagingRNG.selectWinningTickets(totalTickets, totalWinners);

      let ticketIndex = 0;
      for (const prize of prizes) {
        for (let i = 0; i < prize.count; i++) {
          if (ticketIndex >= winningTickets.length) break;

          await createInstantWinPrize({
            UID: crypto.randomUUID(),
            competitionId: competitionUid,
            winningTicket: winningTickets[ticketIndex],
            prize: prize.prize,
            url: prize.url,
            description: prize.description,
            priority: prize.priority,
            winningWalletAddress: null,
            avatarUrl: null,
          });

          ticketIndex++;
        }
      }

      return true;
    } catch (error) {
      console.error('Error generating winning tickets:', error);
      return false;
    }
  },

  /**
   * Auto-generate default prizes for a competition
   *
   * @deprecated For new competitions, use CompetitionSystemV3 contract
   */
  async autoGenerateDefaultPrizes(
    competitionUid: string,
    totalTickets: number,
    prizeValue: number
  ): Promise<boolean> {
    console.warn(
      '[instantWinHelper] autoGenerateDefaultPrizes is for legacy support. ' +
      'New competitions use on-chain VRF via CompetitionSystemV3.'
    );

    const defaultPrizes = [
      {
        prize: `$${Math.floor(prizeValue * 0.4)} Grand Prize`,
        count: 1,
        url: 'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/bitcoin-image.webp',
        description: 'Main grand prize',
        priority: 1,
      },
      {
        prize: `$${Math.floor(prizeValue * 0.15)} Second Prize`,
        count: 2,
        url: 'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/Eth%20Tier%201.png',
        description: 'Runner up prize',
        priority: 2,
      },
      {
        prize: `$${Math.floor(prizeValue * 0.05)} Third Prize`,
        count: 3,
        url: 'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/soltier1.jpg',
        description: 'Third place prize',
        priority: 3,
      },
      {
        prize: `$${Math.floor(prizeValue * 0.01)} Consolation`,
        count: 10,
        url: 'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/nft.webp',
        description: 'Consolation prize',
        priority: 4,
      },
    ];

    return await this.generateWinningTicketsForCompetition(
      competitionUid,
      totalTickets,
      defaultPrizes
    );
  },

  /**
   * Check if a ticket is a winner and notify the user
   *
   * For CompetitionSystemV3:
   * - Instant wins are detected via contract events
   * - This function can be called to update database records
   *
   * @param userId - User's wallet address or ID
   * @param competitionId - Competition UID
   * @param ticketNumber - The ticket number to check
   * @returns Whether the ticket was a winner
   */
  async checkAndNotifyWinner(
    userId: string,
    competitionId: string,
    ticketNumber: number
  ): Promise<boolean> {
    try {
      const { supabase } = await import('./supabase');

      const { data: prize, error } = await supabase
        .from('Prize_Instantprizes')
        .select('*')
        .eq('competitionId', competitionId)
        .eq('winningTicket', ticketNumber)
        .is('winningWalletAddress', null)
        .single();

      if (error || !prize) {
        return false;
      }

      await supabase
        .from('Prize_Instantprizes')
        .update({
          winningWalletAddress: userId,
        })
        .eq('UID', prize.UID);

      const { notificationService } = await import('./notification-service');
      await notificationService.notifyWinner(toPrizePid(userId), competitionId, prize.prize);

      return true;
    } catch (error) {
      console.error('Error checking winner:', error);
      return false;
    }
  },

  /**
   * Record a contract-based instant win in the database
   *
   * This syncs on-chain InstantWin events to the database for tracking.
   *
   * @param competitionUid - Competition UID
   * @param winnerAddress - Winner's wallet address
   * @param ticketNumber - Winning ticket number
   * @param tierId - Prize tier ID from contract
   */
  async recordContractInstantWin(
    competitionUid: string,
    winnerAddress: string,
    ticketNumber: number,
    tierId: string
  ): Promise<boolean> {
    try {
      const { supabase } = await import('./supabase');

      // Check if already recorded
      const { data: existing } = await supabase
        .from('Prize_Instantprizes')
        .select('UID')
        .eq('competitionId', competitionUid)
        .eq('winningTicket', ticketNumber)
        .single();

      if (existing) {
        // Update existing record with winner
        await supabase
          .from('Prize_Instantprizes')
          .update({ winningWalletAddress: winnerAddress })
          .eq('UID', existing.UID);
      } else {
        // Create new record for contract-based win
        await supabase
          .from('Prize_Instantprizes')
          .insert({
            UID: crypto.randomUUID(),
            competitionId: competitionUid,
            winningTicket: ticketNumber,
            prize: `Contract Prize: ${tierId}`,
            winningWalletAddress: winnerAddress,
            url: '',
            description: `On-chain instant win (tier: ${tierId})`,
            priority: 0,
          });
      }

      // Notify winner
      const { notificationService } = await import('./notification-service');
      await notificationService.notifyWinner(winnerAddress, competitionUid, `Instant Win: ${tierId}`);

      return true;
    } catch (error) {
      console.error('Error recording contract instant win:', error);
      return false;
    }
  },

  /**
   * Sync all InstantWin events from contract to database
   *
   * Useful for:
   * - Initial sync after deployment
   * - Recovery after database issues
   * - Admin reporting
   *
   * @param competitionId - On-chain competition ID
   * @param competitionUid - Database competition UID
   */
  async syncContractWinsToDatabase(
    competitionId: number,
    competitionUid: string
  ): Promise<{ synced: number; errors: number }> {
    const { getPublicClient, CONTRACT_ADDRESS, COMPETITION_SYSTEM_ABI } = await import('./competitionSystemV3');

    const publicClient = getPublicClient();
    let synced = 0;
    let errors = 0;

    try {
      // Get all InstantWin events for this competition
      const logs = await publicClient.getContractEvents({
        address: CONTRACT_ADDRESS,
        abi: COMPETITION_SYSTEM_ABI,
        eventName: 'InstantWin' as any,
        args: {
          competitionId: BigInt(competitionId)
        },
        fromBlock: 'earliest'
      });

      for (const log of logs) {
        const args = log.args as {
          buyer?: `0x${string}`;
          ticketNumber?: bigint;
          tierId?: `0x${string}`;
        };

        if (args.buyer && args.ticketNumber !== undefined && args.tierId) {
          const success = await this.recordContractInstantWin(
            competitionUid,
            args.buyer,
            Number(args.ticketNumber),
            args.tierId
          );

          if (success) {
            synced++;
          } else {
            errors++;
          }
        }
      }
    } catch (error) {
      console.error('Error syncing contract wins:', error);
      errors++;
    }

    return { synced, errors };
  }
};
