-- ============================================================================
-- CREATE 12 TEST COMPETITIONS FOR PAY WITH BALANCE TESTING
-- 6 Regular Competitions + 6 Instant Win Competitions
-- All with 2,500-3,000 tickets, various prices, VRF enabled
-- ============================================================================

-- Image URLs from Supabase storage
-- Base: https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/

-- ============================================================================
-- REGULAR COMPETITIONS (6)
-- ============================================================================

-- 1. Bitcoin Draw - $0.10 per ticket, 2500 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'Bitcoin Bonanza',
  'Enter for a chance to win Bitcoin! Experience the thrill of crypto with this epic draw. Each ticket brings you closer to the ultimate crypto prize. VRF-verified for provably fair results.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/bitcoin-image.webp',
  0.10,
  2500,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  1,
  1,
  '0.25 BTC Grand Prize',
  'crypto',
  1500.00,
  false,
  true,
  'pending',
  'crypto',
  10,
  false
);

-- 2. Ethereum Mega - $0.25 per ticket, 2700 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'Ethereum Mega Draw',
  'The ultimate Ethereum giveaway! Stack your ETH with this mega competition. Every ticket purchased increases your chances of winning big. Secured by VRF for guaranteed fairness.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/Eth%20Tier%201.png',
  0.25,
  2700,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  1,
  1,
  '2 ETH Grand Prize',
  'crypto',
  3000.00,
  false,
  true,
  'pending',
  'crypto',
  10,
  false
);

-- 3. Solana Slam - $0.50 per ticket, 2600 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'Solana Slam',
  'Fast transactions, fast wins! Join the Solana revolution with this exciting draw. The speed of Solana meets the thrill of winning. VRF-powered randomness ensures fair play.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/soltier1.jpg',
  0.50,
  2600,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  2,
  2,
  '50 SOL + 25 SOL Runner-up',
  'crypto',
  2500.00,
  false,
  false,
  'pending',
  'crypto',
  10,
  false
);

-- 4. NFT Extravaganza - $0.75 per ticket, 2800 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'NFT Extravaganza',
  'Win exclusive digital art! This NFT collection includes rare pieces from top artists. Your chance to own a piece of digital history. Verified fair selection via VRF.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/nft.webp',
  0.75,
  2800,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  3,
  3,
  'Rare NFT Collection (3 Winners)',
  'nft',
  5000.00,
  false,
  true,
  'pending',
  'nft',
  10,
  false
);

-- 5. Crypto Bundle Supreme - $1.00 per ticket, 3000 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'Crypto Bundle Supreme',
  'The ultimate crypto portfolio starter! Win a diversified bundle of BTC, ETH, SOL, and more. Perfect for building your dream portfolio. Provably fair with blockchain-verified randomness.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/Tier%201%20(1).jpg',
  1.00,
  3000,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  1,
  1,
  'Mixed Crypto Bundle Worth $5000',
  'crypto',
  5000.00,
  false,
  true,
  'pending',
  'crypto',
  10,
  false
);

-- 6. Altcoin Adventure - $0.25 per ticket, 2550 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  deleted
) VALUES (
  'Altcoin Adventure',
  'Discover the next big thing! Win a curated selection of promising altcoins. From DeFi to Layer 2s, this bundle has it all. Fair winner selection powered by VRF.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/bitcoin-image.webp',
  0.25,
  2550,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  5,
  5,
  'Altcoin Package (5 Winners)',
  'crypto',
  2000.00,
  false,
  false,
  'pending',
  'crypto',
  10,
  false
);

-- ============================================================================
-- INSTANT WIN COMPETITIONS (6)
-- ============================================================================

-- 7. Instant Bitcoin Blitz - $0.10 per ticket, 2500 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant Bitcoin Blitz',
  'Instant wins, instant thrills! Buy a ticket and instantly find out if you''ve won Bitcoin. Multiple prize tiers from micro-sats to major BTC prizes. VRF-verified instant reveal.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/bitcoin-image.webp',
  0.10,
  2500,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  25,
  25,
  'Instant Bitcoin Prizes - Multiple Tiers!',
  'crypto',
  1000.00,
  true,
  true,
  'pending',
  'crypto',
  15,
  25,
  false
);

-- 8. Instant Ethereum Rush - $0.25 per ticket, 2700 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant Ethereum Rush',
  'Feel the rush of instant ETH wins! Every ticket is a chance for immediate rewards. From gas money to full ETH prizes. Blockchain-verified fairness guaranteed.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/Eth%20Tier%201.png',
  0.25,
  2700,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  30,
  30,
  'Instant ETH Prizes - Check & Win!',
  'crypto',
  2000.00,
  true,
  true,
  'pending',
  'crypto',
  15,
  30,
  false
);

-- 9. Instant Solana Speed - $0.50 per ticket, 2600 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant Solana Speed',
  'Lightning fast wins on the Solana network! Experience the speed of instant rewards. Multiple SOL prizes available across all tiers. VRF-powered instant validation.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/soltier1.jpg',
  0.50,
  2600,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  20,
  20,
  'Instant SOL Rewards - Fast Wins!',
  'crypto',
  1500.00,
  true,
  false,
  'pending',
  'crypto',
  15,
  20,
  false
);

-- 10. Instant NFT Reveal - $0.75 per ticket, 2800 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant NFT Reveal',
  'Scratch and reveal your NFT prize! Instant gratification meets digital art. Win exclusive NFTs the moment you purchase. Provably fair with on-chain verification.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/nft.webp',
  0.75,
  2800,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  35,
  35,
  'Instant NFT Drops - Reveal & Win!',
  'nft',
  3500.00,
  true,
  true,
  'pending',
  'nft',
  15,
  35,
  false
);

-- 11. Instant Crypto Jackpot - $1.00 per ticket, 3000 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant Crypto Jackpot',
  'The biggest instant win prizes! Premium tickets for premium rewards. Multiple jackpot tiers from small wins to life-changing amounts. VRF ensures every reveal is fair.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/Tier%201%20(1).jpg',
  1.00,
  3000,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  40,
  40,
  'Instant Jackpot - Mega Prizes!',
  'crypto',
  6000.00,
  true,
  true,
  'pending',
  'crypto',
  15,
  40,
  false
);

-- 12. Instant Altcoin Scratch - $0.25 per ticket, 2550 tickets
INSERT INTO competitions (
  title,
  description,
  image_url,
  ticket_price,
  total_tickets,
  sold_tickets,
  tickets_sold,
  status,
  start_time,
  start_date,
  end_time,
  end_date,
  winner_count,
  num_winners,
  prize_description,
  prize_type,
  prize_value,
  is_instant_win,
  is_featured,
  vrf_status,
  category,
  max_tickets_per_user_percentage,
  winning_ticket_count,
  deleted
) VALUES (
  'Instant Altcoin Scratch',
  'Scratch your way to altcoin riches! Instant reveal of diverse crypto prizes. Win tokens from the hottest projects in DeFi, gaming, and more. Fair randomness via VRF.',
  'https://mthwfldcjvpxjtmrqkqm.supabase.co/storage/v1/object/public/Competition%20Images/Competition%20Images/bitcoin-image.webp',
  0.25,
  2550,
  0,
  0,
  'active',
  NOW(),
  NOW()::date,
  NOW() + INTERVAL '14 days',
  (NOW() + INTERVAL '14 days')::date,
  28,
  28,
  'Instant Altcoin Prizes - Scratch & Win!',
  'crypto',
  1800.00,
  true,
  false,
  'pending',
  'crypto',
  15,
  28,
  false
);

-- ============================================================================
-- VERIFICATION QUERY
-- Run after inserting to verify all 12 competitions were created
-- ============================================================================

SELECT 
  id,
  title,
  ticket_price,
  total_tickets,
  status,
  is_instant_win,
  is_featured,
  vrf_status,
  prize_value
FROM competitions
WHERE created_at > NOW() - INTERVAL '5 minutes'
ORDER BY is_instant_win, title;
