/**
 * Competition Page Text Configuration
 * 
 * This file contains the text content for individual competition pages.
 * These values can be edited through the visual editor at /a/e/o/x/u/editor
 * and will directly affect all live competition pages on the site.
 * 
 * To update these values:
 * 1. Go to /a/e/o/x/u/editor
 * 2. Select "Individual Competition Page" from the dropdown
 * 3. Edit the text fields under "Text Content"
 * 4. Download the updated file
 * 5. Replace this file with the downloaded version
 * 6. Commit and deploy
 */

export const competitionPageConfig = {
  ticketNumbersDescription: "Ticket numbers are randomly generated once you make your payment. The system will automatically check the ticket numbers that you get and will match them with the winning numbers above and you will instantly win that prize! If your ticket number matches the number generated by the auto draw system at the end of the competition, you will also win the end prize of £500 cash!",
  picturesDisclaimer: "*Pictures are for illustration purposes only*",
  minimumWinText: "Every ticket will win a minimum of £1.00 site credit!",
  additionalInfo: "", // Optional additional text to display
};

export type CompetitionPageConfig = typeof competitionPageConfig;
