// Text overrides for visual editor live preview
export interface CompetitionPageTextOverrides {
  competitionTitle?: string;
  ticketNumbersDescription?: string;
  picturesDisclaimer?: string;
  minimumWinText?: string;
  additionalInfo?: string;
}

interface IndividualCompetitionInfoProps {
  // Optional text overrides for visual editor live preview
  textOverrides?: CompetitionPageTextOverrides;
}

const IndividualCompetitionInfo = ({ textOverrides }: IndividualCompetitionInfoProps) => {
    return (
        <div className="text-white text-center max-w-7xl mx-auto">
            <h1 className="sequel-95 lg:text-4xl text-2xl">
                {textOverrides?.competitionTitle || "Competition Title"}
            </h1>
            <div className="sequel-45 leading-loose my-8 lg:text-lg text-center xl:w-9/12 mx-auto">
                <p>
                    {textOverrides?.ticketNumbersDescription || 
                     "Ticket numbers are randomly generated once you make your payment. The system will automatically check the ticket numbers that you get and will match them with the winning numbers above and you will instantly win that prize! If your ticket number matches the number generated by the auto draw system at the end of the competition, you will also win the end prize of £500 cash!"}
                </p>
                <p>
                    {textOverrides?.picturesDisclaimer || "*Pictures are for illustration purposes only*"}
                </p>
                {textOverrides?.additionalInfo && (
                    <p>{textOverrides.additionalInfo}</p>
                )}
            </div>
            <p className="sequel-75 mt-6 lg:text-lg">
                {textOverrides?.minimumWinText || "Every ticket will win a minimum of £1.00 site credit!"}
            </p>
        </div>
    )
}

export default IndividualCompetitionInfo