/*\n  # Comprehensive Schema Cleanup - Fix ALL Duplicate Columns V2\n  \n  ## Critical Issues Fixed\n  \n  ### Tables with Duplicate Columns (SEVERE DATABASE CORRUPTION)\n  1. **competitions** - 14 duplicate columns\n  2. **participants** - 6 duplicate columns  \n  3. **profiles** - 4 duplicate columns\n  4. **transactions** - 8 duplicate columns\n  5. **winners** - 10 duplicate columns\n  \n  ## Strategy\n  For each corrupted table:\n  1. Create new clean table with `_clean` suffix\n  2. Copy data from old table (Postgres will use first column definition)\n  3. Drop old table\n  4. Rename clean table to original name\n  5. Recreate all constraints, indexes, and foreign keys\n  \n  ## Data Safety\n  - All existing data is preserved\n  - Foreign key relationships maintained\n*/\n\n-- ==========================================\n-- 1. FIX COMPETITIONS TABLE\n-- ==========================================\n\nCREATE TABLE IF NOT EXISTS competitions_clean (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  creator_id uuid,\n  title text,\n  description text,\n  contract_address text,\n  chain_id integer DEFAULT 11155111,\n  max_participants integer,\n  entry_fee text,\n  status text DEFAULT 'active',\n  winner_address text,\n  tx_hash text,\n  vrf_request_id text,\n  created_at timestamptz DEFAULT now(),\n  drawn_at timestamptz,\n  prize_type text DEFAULT 'cash',\n  competition_type text DEFAULT 'standard',\n  is_featured boolean DEFAULT false,\n  uid text UNIQUE,\n  imageurl text,\n  image_url text,\n  prize_value numeric,\n  ticket_price numeric DEFAULT 0.99,\n  total_tickets integer,\n  tickets_sold integer DEFAULT 0,\n  start_date timestamptz DEFAULT now(),\n  end_date timestamptz,\n  draw_date timestamptz,\n  is_instant_win boolean DEFAULT false,\n  font_size_override text,\n  font_weight_override text,\n  metadata_title text,\n  metadata_description text,\n  metadata_image text,\n  competitionended integer DEFAULT 0,\n  crdate timestamptz DEFAULT now()\n);
\n\nINSERT INTO competitions_clean \nSELECT DISTINCT ON (id)\n  id, creator_id, title, description, contract_address, chain_id,\n  max_participants, entry_fee, status, winner_address, tx_hash, vrf_request_id,\n  created_at, drawn_at, prize_type, competition_type, is_featured, uid,\n  imageurl, image_url, prize_value, ticket_price, total_tickets, tickets_sold,\n  start_date, end_date, draw_date, is_instant_win, font_size_override,\n  font_weight_override, metadata_title, metadata_description, metadata_image,\n  competitionended, crdate\nFROM competitions\nWHERE id IS NOT NULL;
\n\nDROP TABLE IF EXISTS competitions CASCADE;
\nALTER TABLE competitions_clean RENAME TO competitions;
\n\nCREATE INDEX IF NOT EXISTS idx_competitions_uid ON competitions(uid);
\nCREATE INDEX IF NOT EXISTS idx_competitions_ended ON competitions(competitionended);
\nCREATE INDEX IF NOT EXISTS idx_competitions_crdate ON competitions(crdate);
\nCREATE INDEX IF NOT EXISTS idx_competitions_status ON competitions(status);
\n\n-- ==========================================\n-- 2. FIX PARTICIPANTS TABLE\n-- ==========================================\n\nCREATE TABLE IF NOT EXISTS participants_clean (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  competition_id uuid,\n  user_id uuid,\n  wallet_address text,\n  tx_hash text,\n  joined_at timestamptz DEFAULT now()\n);
\n\nINSERT INTO participants_clean\nSELECT DISTINCT ON (id)\n  id, competition_id, user_id, wallet_address, tx_hash, joined_at\nFROM participants\nWHERE id IS NOT NULL;
\n\nDROP TABLE IF EXISTS participants CASCADE;
\nALTER TABLE participants_clean RENAME TO participants;
\n\n-- ==========================================\n-- 3. FIX PROFILES TABLE\n-- ==========================================\n\nCREATE TABLE IF NOT EXISTS profiles_clean (\n  id uuid PRIMARY KEY,\n  wallet_address text,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\nINSERT INTO profiles_clean\nSELECT DISTINCT ON (id)\n  id, wallet_address, created_at, updated_at\nFROM profiles\nWHERE id IS NOT NULL;
\n\nDROP TABLE IF EXISTS profiles CASCADE;
\nALTER TABLE profiles_clean RENAME TO profiles;
\n\n-- ==========================================\n-- 4. FIX TRANSACTIONS TABLE  \n-- ==========================================\n\nCREATE TABLE IF NOT EXISTS transactions_clean (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid,\n  competition_id uuid,\n  tx_hash text UNIQUE,\n  tx_type text,\n  status text DEFAULT 'pending',\n  created_at timestamptz DEFAULT now(),\n  confirmed_at timestamptz\n);
\n\nINSERT INTO transactions_clean\nSELECT DISTINCT ON (id)\n  id, user_id, competition_id, tx_hash, tx_type, status, created_at, confirmed_at\nFROM transactions\nWHERE id IS NOT NULL;
\n\nDROP TABLE IF EXISTS transactions CASCADE;
\nALTER TABLE transactions_clean RENAME TO transactions;
\n\n-- ==========================================\n-- 5. FIX WINNERS TABLE (with correct case)\n-- ==========================================\n\nCREATE TABLE IF NOT EXISTS winners_clean (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  competition_id uuid,\n  user_id uuid,\n  wallet_address text,\n  prize_amount text,\n  claimed boolean DEFAULT false,\n  won_at timestamptz DEFAULT now(),\n  is_promoted boolean DEFAULT false,\n  vrf_request_id varchar,\n  vrf_proof varchar,\n  tx_hash text,\n  username text,\n  country text,\n  prize text,\n  "isShow" boolean DEFAULT true,\n  crdate timestamptz DEFAULT now(),\n  is_instant_win boolean DEFAULT false,\n  ticket_number integer,\n  prize_value numeric,\n  prize_claimed boolean DEFAULT false,\n  uid text\n);
\n\nINSERT INTO winners_clean\nSELECT DISTINCT ON (id)\n  id, competition_id, user_id, wallet_address, prize_amount, claimed, won_at,\n  is_promoted, vrf_request_id, vrf_proof, tx_hash, username, country, prize,\n  "isShow", crdate, is_instant_win, ticket_number, prize_value, prize_claimed, uid\nFROM winners\nWHERE id IS NOT NULL;
\n\nDROP TABLE IF EXISTS winners CASCADE;
\nALTER TABLE winners_clean RENAME TO winners;
\n\n-- ==========================================\n-- 6. RECREATE FOREIGN KEYS\n-- ==========================================\n\nALTER TABLE tickets DROP CONSTRAINT IF EXISTS tickets_competition_id_fkey;
\nALTER TABLE tickets DROP CONSTRAINT IF EXISTS tickets_user_id_fkey;
\nALTER TABLE tickets ADD CONSTRAINT tickets_competition_id_fkey \n  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE;
\n\nALTER TABLE user_entries DROP CONSTRAINT IF EXISTS user_entries_competition_id_fkey;
\nALTER TABLE user_entries ADD CONSTRAINT user_entries_competition_id_fkey\n  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE;
\n\nALTER TABLE participants ADD CONSTRAINT participants_competition_id_fkey\n  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE;
\n\nALTER TABLE winners ADD CONSTRAINT winners_competition_id_fkey\n  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE;
\n\nALTER TABLE hero_competitions DROP CONSTRAINT IF EXISTS hero_competitions_competition_id_fkey;
\nALTER TABLE hero_competitions ADD CONSTRAINT hero_competitions_competition_id_fkey\n  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE;
\n\n-- ==========================================\n-- 7. ENABLE RLS\n-- ==========================================\n\nALTER TABLE competitions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE participants ENABLE ROW LEVEL SECURITY;
\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
\nALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE winners ENABLE ROW LEVEL SECURITY;
\n\n-- ==========================================\n-- 8. CREATE PUBLIC READ POLICIES\n-- ==========================================\n\nDROP POLICY IF EXISTS "Public read access for competitions" ON competitions;
\nCREATE POLICY "Public read access for competitions"\n  ON competitions FOR SELECT\n  TO public\n  USING (true);
\n\nDROP POLICY IF EXISTS "Public read access for winners" ON winners;
\nCREATE POLICY "Public read access for winners"\n  ON winners FOR SELECT\n  TO public\n  USING (true);
\n;
