/*\n  # Add USDC Balance to User Accounts\n\n  1. Changes\n    - Add `usdc_balance` column to `privy_user_connections` table\n    - Set default value to 0\n    - Add index for performance\n    - Create function to credit user balance\n    - Create function to debit user balance with validation\n  \n  2. Security\n    - Only authenticated users can view their own balance\n    - Balance updates require proper validation\n*/\n\n-- Add USDC balance column\nALTER TABLE privy_user_connections \nADD COLUMN IF NOT EXISTS usdc_balance NUMERIC(10, 2) DEFAULT 0 NOT NULL;
\n\n-- Add index for faster balance queries\nCREATE INDEX IF NOT EXISTS idx_privy_user_connections_usdc_balance \nON privy_user_connections(usdc_balance);
\n\n-- Function to credit user balance (for deposits)\nCREATE OR REPLACE FUNCTION credit_user_balance(\n  user_id TEXT,\n  amount NUMERIC\n)\nRETURNS NUMERIC\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  new_balance NUMERIC;
\nBEGIN\n  IF amount <= 0 THEN\n    RAISE EXCEPTION 'Credit amount must be positive';
\n  END IF;
\n\n  UPDATE privy_user_connections\n  SET usdc_balance = usdc_balance + amount\n  WHERE privy_did = user_id\n  RETURNING usdc_balance INTO new_balance;
\n\n  IF NOT FOUND THEN\n    RAISE EXCEPTION 'User not found';
\n  END IF;
\n\n  RETURN new_balance;
\nEND;
\n$$;
\n\n-- Function to debit user balance (for ticket purchases)\nCREATE OR REPLACE FUNCTION debit_user_balance(\n  user_id TEXT,\n  amount NUMERIC\n)\nRETURNS NUMERIC\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  current_balance NUMERIC;
\n  new_balance NUMERIC;
\nBEGIN\n  IF amount <= 0 THEN\n    RAISE EXCEPTION 'Debit amount must be positive';
\n  END IF;
\n\n  SELECT usdc_balance INTO current_balance\n  FROM privy_user_connections\n  WHERE privy_did = user_id;
\n\n  IF NOT FOUND THEN\n    RAISE EXCEPTION 'User not found';
\n  END IF;
\n\n  IF current_balance < amount THEN\n    RAISE EXCEPTION 'Insufficient balance';
\n  END IF;
\n\n  UPDATE privy_user_connections\n  SET usdc_balance = usdc_balance - amount\n  WHERE privy_did = user_id\n  RETURNING usdc_balance INTO new_balance;
\n\n  RETURN new_balance;
\nEND;
\n$$;
\n\n-- Update get_user_wallet_balance to return USDC balance\nCREATE OR REPLACE FUNCTION get_user_wallet_balance(user_identifier TEXT)\nRETURNS NUMERIC\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nBEGIN\n  RETURN (\n    SELECT COALESCE(usdc_balance, 0)\n    FROM privy_user_connections\n    WHERE privy_did = user_identifier\n       OR wallet_address = user_identifier\n       OR email = user_identifier\n    LIMIT 1\n  );
\nEND;
\n$$;
;
