-- ============================================================================
-- Production Schema Sync Migration
-- Generated from production Supabase CSV exports
-- Date: 2026-02-18
-- ============================================================================
--
-- This migration ensures the local schema matches the production database
-- by creating all functions, indexes, and triggers from production CSVs.
--
-- Statistics:
-- - 0 public functions
-- - 0 public indexes
-- - 0 trigger functions
-- - 0 triggers
--
-- ============================================================================

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
